DROP TABLE IF EXISTS MARMITA;
DROP TABLE IF EXISTS TAMANHO;
DROP TABLE IF EXISTS MARMITA_TEM;
DROP TABLE IF EXISTS RESTAURANTE;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS PEDIDO_CONTEM;
DROP TABLE IF EXISTS SELF_SERVICE;
DROP TABLE IF EXISTS CARDAPIO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS ATENDENTE;
DROP TABLE IF EXISTS COZINHEIRO;
DROP TABLE IF EXISTS ENTREGADOR;
DROP TABLE IF EXISTS ADMINISTRADOR;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS EMBALAGEM;
DROP TABLE IF EXISTS FORNECEDOR;

CREATE TABLE MARMITA (CODIGO INTEGER, NOME VARCHAR(255), MISTURA VARCHAR(255), DESCRICAO VARCHAR(255),
    CONSTRAINT CHAVE_MARMITA PRIMARY KEY (CODIGO)
);
CREATE TABLE TAMANHO (MEDIDA VARCHAR(2), DESCRICAO VARCHAR(255), QUANTIDADE VARCHAR(255),
    CONSTRAINT CHAVE_TAMANHO PRIMARY KEY (MEDIDA)
);
CREATE TABLE MARMITA_TEM (CODIGO_MARMITA INTEGER, MEDIDA_TAMANHO VARCHAR(255),
    FOREIGN KEY (CODIGO_MARMITA) REFERENCES MARMITA(CODIGO),
    FOREIGN KEY (MEDIDA_TAMANHO) REFERENCES TAMANHO(MEDIDA),
    PRIMARY KEY (CODIGO_MARMITA, MEDIDA_TAMANHO)
);
CREATE TABLE RESTAURANTE (NOME VARCHAR(9),ENDERECO VARCHAR(255), TELEFONE VARCHAR(255),
    PRIMARY KEY (NOME_RESTAURANTE)
);
CREATE TABLE SELF_SERVICE (TIPO CHAR(9),PREÇO VARCHAR(255), QUANTIDADE VARCHAR(255),
    PRIMARY KEY (TIPO)
);
CREATE TABLE CARDAPIO (PRATO_DO_DIA CHAR(9),BEBIDAS VARCHAR(255),
    PRIMARY KEY (TIPO)
);
CREATE TABLE PEDIDO (NUM INTEGER, ENDERECO VARCHAR(255), DATA_PEDIDO VARCHAR(10), VALOR VARCHAR(255),
    TELEFONE_CLIENTE CHAR(9),
    ID_ENTREGADOR INTEGER,
    ID_ATENDENTE INTEGER,
    TEL CHAR(9),
    FOREIGN KEY (TEL) REFERENCES CLIENTE(TELEFONE),
    FOREIGN KEY(ID_ENTREGADOR) REFERENCES ENTREGADOR(ID_ENTREGADOR),
    FOREIGN KEY (ID_ATENDENTE) REFERENCES ATENDENTE(ID_ATENDENTE),            
    PRIMARY KEY (NUM)
);
CREATE TABLE PEDIDO_TEM(NUM_PEDIDO INTEGER, COD_MARMITA INTEGER, MEDIDA_TAMANHO VARCHAR(2),
    FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO(NUM),
    FOREIGN KEY (NUMERO_MARMITA) REFERENCES MARMITA(COD),
    FOREIGN KEY (MEDIDA_TAMANHO) REFERENCES TAMANHO(MEDIDA),
    PRIMARY KEY (NUM_PEDIDO, COD_MARMITA, MEDIDA_TAMANHO)
);
CREATE TABLE CLIENTE (TELEFONE CHAR(9),NOME VARCHAR(255), EMAIL VARCHAR(255),
    NOME_BAIRRO VARCHAR(255),
    FOREIGN KEY (NOME_BAIRRO) REFERENCES BAIRRO(NOME),
    PRIMARY KEY (TELEFONE)
);
CREATE TABLE BAIRRO (NOME VARCHAR(255), TEMPO TIME, REFERENCIA VARCHAR(255),
    PRIMARY KEY (NOME)
);
CREATE TABLE ATENDENTE (ID_ATENDENTE INTEGER,
    FOREIGN KEY (ID_ATENDENTE) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (ID_ATENDENTE)
);
CREATE TABLE COZINHEIRO (ID_COZINHEIRO INTEGER, CPF VARCHAR(11), CATEGORIA VARCHAR(15), TELEFONE CHAR(9),
    FOREIGN KEY (ID_COZINHEIRO) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (ID_COZINHEIRO)
);
CREATE TABLE ENTREGADOR (ID_ENTREGADOR INTEGER, TELEFONE CHAR(9),
    FOREIGN KEY (ID_ENTREGADOR) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (ID_ENTREGADOR)
);
CREATE TABLE ADMINISTRADOR (ID_ADMINISTRADOR INTEGER, CPF VARCHAR(11), TELEFONE CHAR(9), EMAIL VARCHAR(255),
    FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (ID_ADMINISTRADOR)
);
CREATE TABLE FUNCIONARIO (ID INTEGER, SALARIO VARCHAR(255), SEXO VARCHAR(1), NOME VARCHAR(255),
    PRIMARY KEY (ID)
);
CREATE TABLE EMBALAGEM(ID INTEGER, PRECO_UNITARIO VARCHAR(255), DESCRICAO VARCHAR(255), ID_GERENTE INTEGER, CNPJ_FORNECEDOR VARCHAR(12),
    FOREIGN KEY (ID_GERENTE) REFERENCES GERENTE(ID_GERENTE),
    FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ),
    PRIMARY KEY (ID)
);
CREATE TABLE FORNECEDOR(CNPJ VARCHAR(12), NOME_EMPRESA VARCHAR(255), TELEFONE CHAR(9),
    PRIMARY KEY (CNPJ)
);
/* https://github.com/ThiagoRobertoj/Projeto-de-BD.git */
/*um adendo é que fiz umas alterações no modelo de entidade relacional pq enquanto fazia as tables percebi que n fazia sentido a relação de restaurante e contem marmita então criei uma nova table chamada pedido e atualizei o arquivo no githib*/