DROP DATABASE IF EXISTS Restautant;
CREATE DATABASE Restaurant;
USE Restaurant;

CREATE TABLE MARMITA (CODIGO INTEGER, MISTURA VARCHAR(255), DESCRICAO VARCHAR(255),
    CONSTRAINT CHAVE_MARMITA PRIMARY KEY (CODIGO)
);
CREATE TABLE TAMANHO (MEDIDA VARCHAR(2), DESCRICAO VARCHAR(255), QUANTIDADE VARCHAR(255),
    CONSTRAINT CHAVE_TAMANHO PRIMARY KEY (MEDIDA)
);
CREATE TABLE MARMITA_TEM (CODIGO_MARMITA INTEGER, MEDIDA_TAMANHO VARCHAR(255),
    FOREIGN KEY (CODIGO_MARMITA) REFERENCES MARMITA(CODIGO),
    FOREIGN KEY (MEDIDA_TAMANHO) REFERENCES TAMANHO(MEDIDA),
    PRIMARY KEY (CODIGO_MARMITA, MEDIDA_TAMANHO)
);
CREATE TABLE RESTAURANTE (NOME VARCHAR(9),ENDERECO VARCHAR(255), TELEFONE VARCHAR(255),
    PRIMARY KEY (NOME)
);
CREATE TABLE SELF_SERVICE (TIPO CHAR(9),PREÇO VARCHAR(255), QUANTIDADE VARCHAR(255),
    PRIMARY KEY (TIPO)
);
CREATE TABLE CARDAPIO (PRATO_DO_DIA CHAR(9),BEBIDAS VARCHAR(255),
    PRIMARY KEY (PRATO_DO_DIA)
);
CREATE TABLE PEDIDO (NUM INTEGER, ENDERECO VARCHAR(255), DATA_PEDIDO VARCHAR(10), VALOR VARCHAR(255),
    TELEFONE_CLIENTE CHAR(9),
    ID_ENTREGADOR INTEGER,
    ID_ATENDENTE INTEGER,
    TEL CHAR(9),
    FOREIGN KEY (TEL) REFERENCES CLIENTE(TELEFONE),
    FOREIGN KEY(CARTEIRA_MOTORISTA) REFERENCES ENTREGADOR(CARTEIRA_MOTORISTA),
    FOREIGN KEY (ID_ATENDENTE) REFERENCES ATENDENTE(ID_ATENDENTE),            
    PRIMARY KEY (NUM)
);
CREATE TABLE PEDIDO_TEM(NUM_PEDIDO INTEGER, COD_MARMITA INTEGER, MEDIDA_TAMANHO VARCHAR(2),
    FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO(NUM),
    FOREIGN KEY (NUMERO_MARMITA) REFERENCES MARMITA(CODIGO),
    FOREIGN KEY (MEDIDA_TAMANHO) REFERENCES TAMANHO(MEDIDA),
    PRIMARY KEY (NUM_PEDIDO, COD_MARMITA, MEDIDA_TAMANHO)
);
CREATE TABLE CLIENTE (TELEFONE CHAR(9),NOME VARCHAR(255), EMAIL VARCHAR(255),
    NOME_BAIRRO VARCHAR(255),
    FOREIGN KEY (NOME_BAIRRO) REFERENCES BAIRRO(NOME),
    PRIMARY KEY (TELEFONE)
);
CREATE TABLE BAIRRO (NOME VARCHAR(255), TEMPO TIME, REFERENCIA VARCHAR(255),
    PRIMARY KEY (NOME)
);
CREATE TABLE ATENDENTE (CPF_ATENDENTE INTEGER, NOME_ATENDENTE VARCHAR(255),
    FOREIGN KEY (CPF_ATENDENTE) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (CPF_ATENDENTE));
CREATE TABLE COZINHEIRO (TELEFONE CHAR(9), NOME_COZINHEIRO VARCHAR(255), CPF_COZINHEIRO INTEGER,
    PRIMARY KEY (CPF_COZINHEIRO),
    FOREIGN KEY (CPF_COZINHEIRO) REFERENCES FUNCIONARIO(ID)
);
CREATE TABLE ENTREGADOR (CARTEIRA_MOTORISTA INTEGER, TELEFONE CHAR(9),
    FOREIGN KEY (CARTEIRA_MOTORISTA) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (CARTEIRA_MOTORISTA)
);
CREATE TABLE ADMINISTRADOR (ID_ADMINISTRADOR INTEGER, EMAIL VARCHAR(255),
    FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (ID_ADMINISTRADOR)
);
CREATE TABLE FUNCIONARIO (ID INTEGER, SALARIO VARCHAR(255), NOME VARCHAR(255),
    PRIMARY KEY (ID)
);
CREATE TABLE EMBALAGEM(ID INTEGER, PRECO_UNITARIO VARCHAR(255), DESCRICAO VARCHAR(255), ID_GERENTE INTEGER, CNPJ_FORNECEDOR VARCHAR(12),
    FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR),
    FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ),
    PRIMARY KEY (ID)
);
CREATE TABLE FORNECEDOR(CNPJ VARCHAR(12), NOME_EMPRESA VARCHAR(255), TELEFONE CHAR(9),
    PRIMARY KEY (CNPJ)
);
/* https://github.com/ThiagoRobertoj/Projeto-de-BD.git */

